# Your Supabase Database URL
spring.datasource.url=jdbc:postgresql://db.sqgwcunqgcfmtfdjmvms.supabase.co:6543/postgres?sslmode=require

# Username is postgres
spring.datasource.username=postgres

# Replace [YOUR-PASSWORD] with your actual database password (remove the brackets [])
spring.datasource.password=Charan4138@@

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate and Database settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false