spring.datasource.url=jdbc:postgresql://db.sqgwcunqgcfmtfdjmvms.supabase.co:6543/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Charan4138@@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=false